# Generated by Django 5.1.3 on 2024-12-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$YURjSqm7efR09YKDtpACmZ$IvpZTwRQhSFhodDKjm6EfBrFs+LQ0kCTqmYlKRyUJEo=', max_length=128),
        ),
    ]
