# Generated by Django 5.1.3 on 2024-12-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_telegramuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
