# Generated by Django 5.1.3 on 2024-12-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_telegramuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$kvvtAEB56KDhOsq3LcSfpc$bTWhuu3gv9cddR7qIQomW2Z5BJQwEyIRRrTs6fan2I4=', max_length=128),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_id',
            field=models.BigIntegerField(default=123, unique=True),
        ),
    ]
