# Generated by Django 5.1.3 on 2024-12-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_telegramuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='invite_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
