# Generated by Django 5.1.3 on 2024-12-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tetris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tetrisplay',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
