# Generated by Django 5.1.3 on 2024-12-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_amount',
            field=models.IntegerField(default=1),
        ),
    ]
