# Generated by Django 5.1.3 on 2024-12-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_telegramuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelManagers(
            name='telegramuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
