# Generated by Django 5.1.3 on 2024-12-02 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_telegramuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$fEMuxqMh4y6WOqYhFei4kg$tNNiMws2iPTYaXXbdgWw1pKuku/Urgo/PRaeIkqUVaw=', max_length=128),
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_amount', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coins', to='home.telegramuser')),
            ],
        ),
    ]
