# Generated by Django 5.1.3 on 2024-12-02 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_telegramuser_password_coin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Coin',
        ),
        migrations.DeleteModel(
            name='TelegramUser',
        ),
    ]
