# Generated by Django 5.1.3 on 2024-12-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sent_to_all',
            field=models.BooleanField(default=True),
        ),
    ]
