# Generated by Django 5.1.3 on 2024-12-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardblog',
            name='image',
            field=models.ImageField(upload_to='awards_image/'),
        ),
    ]
