# Generated by Django 5.1.3 on 2025-01-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='youtube',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='youtube',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
